name: Apply Terraform 

on: [push]

jobs:
    Run-Terraform:
      runs-on: ubuntu-latest
      steps:
        - uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - run: |
            az account list

                            
        - name: Checkout Source Code
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
            submodules: recursive

        - name: test
          run: |
            pwd
            ls -la

        - name: Change directory to Terraform code
          working-directory: ./Screen.Deploy/terraform
          run: |
            cd ./Screen.Deploy/terraform
            pwd
            ls -la

            # install terraform
        - uses: hashicorp/setup-terraform@v2
          name: setup terraform
        

        - name: Terraform Validate
          run: terraform validate
        
