name: Apply Terraform 

on: [push]

jobs:
    Run-Terraform:
      runs-on: ubuntu-latest
      steps:
        - uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - run: |
            az account list

                            
        - name: Checkout Source Code
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
            submodules: recursive


        - name: Change directory to Terraform code
          working-directory: ./Screen.Deploy/terraform
          run: |
            pwd
            ls -la

        # install terraform
        - uses: hashicorp/setup-terraform@v2
          name: setup terraform

        - name: Initialize Terraform
          run: terraform init

        - name: Terraform Validate
          run: terraform validate
        
        - name: Plan Terraform
          run: terraform plan

        - name: Apply Terraform
          run: terraform apply -auto-approve        
