name: Apply Terraform 
on: [push]

env:
  TERRAFORM_PATH: "./Screen.Deploy/terraform"

jobs:
    Run-Terraform:
      runs-on: ubuntu-latest

      steps:
        - uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - run: |
            az account list

                            
        - name: Checkout Source Code
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
            submodules: recursive


        - name: Change directory to Terraform code
          working-directory: ${{ env.TERRAFORM_PATH }}
          run: |
            pwd
            ls -la

        # # install terraform
        # - uses: hashicorp/setup-terraform@v2
        #   name: setup terraform

        # - name: Initialize Terraform
        #   run: |
        #     pwd
        #     terraform init

        # - name: Terraform Validate
        #   run: | 
        #     pwd
        #     terraform validate

        # - name: Plan Terraform
        #   run: |
        #     pwd
        #     terraform plan

        # - name: Apply Terraform
        #   run: |
        #     pwd
        #     terraform apply -auto-approve        
