name: Screen4_CICD_Pipeline
on: [push]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
  ARTIFACT_NAME: drop
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  IMAGE_NAME: screen.processfunction
  REGISTRY: stevenjiangnz

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: test_run
        run: |
          echo "Hello World" 

      - name: Login to Docker Hub
        run: docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
  

      - name: ACR - Build and push Docker image
        working-directory: ${{ env.working-directory }}
        run: |
          cd ../resources/deploy
          bash build.sh ${{ env.IMAGE_NAME}}

          docker image tag ${{ env.IMAGE_NAME}} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:latest
          docker image push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:latest
